#!/usr/bin/env python3
# ============================================================================
# glm_full_ref_np.py -- CLEAN-ROOM numpy reference of the ASSEMBLED GLM-5.2-FP8
#                       full forward pass, for the committed slice config.
# ----------------------------------------------------------------------------
# PURPOSE (TRACK F0 -- full-model fidelity cross-check)
#   A structurally independent, second implementation of the GLM-5.2-FP8 forward
#   pass:  embed -> N decoder layers { RMSNorm -> MLA attention -> RMSNorm ->
#   MoE/dense FFN, residuals } -> final RMSNorm -> LM head -> argmax.
#
#   It is written from the MODEL description (src/glm_model_fp8.v header,
#   SPEC.md, the GLM/DeepSeek-V3 MoE contract) as a plain transformer, in
#   float64, applying the documented FP8 arithmetic contract (E4M3 weights +
#   [128,128] bf16 block scales + dynamic per-token pow2 activation->E4M3 quant +
#   bf16 tail) at the contract boundaries.
#
#   INDEPENDENCE:
#     * Different language / structure than the Verilog fp64 golden in
#       test/glm_model_fp8_tb.v (the thing we cross-check against).
#     * Independent of tools/glm_fp8_ref.py's arithmetic: that ref uses a
#       DIFFERENT dynamic activation scale (floor(log2(448/amax))) and a
#       bit-exact fixed-point block accumulator; THIS ref uses the pow2
#       activation scale a_shift = clamp(134 - emax_expfield) and a plain
#       float64 block accumulation -- the two would NOT share a systematic
#       bug in the activation-scale / accumulation path.
#
#   The stimulus (weights + inputs) is generated by the SAME deterministic hash
#   generators the TB drives (gen_bf16/gen_e4m3/gen_scale + the build_stimulus
#   sc-counter order), so both implementations see byte-identical test vectors.
#
# OUTPUT: for each committed test vector, the 256 logits (as bf16 codes) and the
#   argmax.  cross_check.py loads the TB golden + RTL-DUT dumps and compares.
# ============================================================================
import numpy as np
import math

# ============================================================================
# slice config (mirror of test/glm_model_fp8_tb.v localparams)
# ============================================================================
MODEL_DIM   = 128
L           = 6
N_DENSE     = 3
VOCAB       = 256
H_HEADS     = 4
NOPE        = 16
ROPE        = 16
V_DIM       = 32
Q_LORA      = 64
KV_LORA     = 32
S_MAX       = 8
THETA       = 8000000
N_EXPERT    = 8
TOPK        = 2
INTER_MOE   = 64
INTER_DENSE = 256
RSCALE      = 2.5
BLK         = 128
EPS         = 1e-5

QK_DIM = NOPE + ROPE            # 32
HQK    = H_HEADS * QK_DIM       # 128
HNOPE  = H_HEADS * NOPE         # 64
HV     = H_HEADS * V_DIM        # 128
FF_NB_D = (max(INTER_DENSE, MODEL_DIM) + BLK - 1) // BLK   # 2

MASK32 = 0xFFFFFFFF


def set_config(**kw):
    """Override the module-level slice config (for the intermediate 2x run).
       Functions read these as globals at call time, so reassigning updates them."""
    g = globals()
    for k, v in kw.items():
        g[k] = v
    g["QK_DIM"] = g["NOPE"] + g["ROPE"]
    g["HQK"] = g["H_HEADS"] * g["QK_DIM"]
    g["HNOPE"] = g["H_HEADS"] * g["NOPE"]
    g["HV"] = g["H_HEADS"] * g["V_DIM"]
    g["FF_NB_D"] = (max(g["INTER_DENSE"], g["MODEL_DIM"]) + g["BLK"] - 1) // g["BLK"]

# ============================================================================
# (A) bf16 as uint16 codes  (round-half-up + flush-to-zero; matches TB real2b)
# ============================================================================
def real2b(v):
    """float -> bf16 code (uint16).  round-half-up on 7-bit mantissa, FTZ."""
    if v == 0.0:
        return 0
    s = 1 if v < 0.0 else 0
    av = abs(v)
    e = 0
    while av >= 2.0:
        av *= 0.5; e += 1
    while av < 1.0:
        av *= 2.0; e -= 1
    mi = int((av - 1.0) * 128.0 + 0.5)     # trunc toward zero; arg>=0 -> floor
    if mi >= 128:
        mi -= 128; e += 1
    if e < -126:
        return (s << 15)                    # underflow -> signed zero (b2real=0)
    ef = e + 127
    return ((s << 15) | ((ef & 0xFF) << 7) | (mi & 0x7F)) & 0xFFFF

def b2real(b):
    """bf16 code -> float.  exp field 0 or 0xFF decode to 0 (matches TB b2real).
       NOTE: coerce to a Python int first -- a numpy uint16 arg would make the
       (ef-127) exponent underflow in unsigned arithmetic."""
    b = int(b) & 0xFFFF
    ef = (b >> 7) & 0xFF
    if ef == 0 or ef == 0xFF:
        return 0.0
    m = b & 0x7F
    val = (1.0 + m / 128.0) * (2.0 ** (ef - 127))
    return -val if (b >> 15) & 1 else val

def bf16(v):
    """round a real to the nearest representable bf16 value (real -> real)."""
    return b2real(real2b(v))

# vectorised b2real over a numpy uint16 array -> float64 array
def b2real_vec(codes):
    codes = np.asarray(codes, dtype=np.uint32)
    ef = (codes >> 7) & 0xFF
    m = codes & 0x7F
    s = (codes >> 15) & 1
    val = (1.0 + m / 128.0) * np.exp2((ef.astype(np.int64) - 127).astype(np.float64))
    val = np.where((ef == 0) | (ef == 0xFF), 0.0, val)
    return np.where(s == 1, -val, val)

# vectorised real2b (float64 array -> uint16 bf16 codes); mirrors scalar real2b
def real2b_vec(v):
    v = np.asarray(v, dtype=np.float64)
    nz = v != 0.0
    s = (v < 0.0).astype(np.uint32)
    av = np.abs(np.where(nz, v, 1.0))
    mant_f, exp_i = np.frexp(av)              # av = mant_f*2^exp, mant_f in [0.5,1)
    m1 = mant_f * 2.0                          # [1,2)
    E = exp_i - 1
    mi = np.floor((m1 - 1.0) * 128.0 + 0.5).astype(np.int64)
    carry = mi >= 128
    mi = np.where(carry, mi - 128, mi)
    E = np.where(carry, E + 1, E)
    ftz = E < -126
    ef = (E + 127).astype(np.int64)
    code = ((s << 15) | ((ef.astype(np.uint32) & 0xFF) << 7) | (mi.astype(np.uint32) & 0x7F))
    code = np.where(ftz, (s << 15), code)
    code = np.where(nz, code, 0).astype(np.uint16)
    return code

def _rne_vec(x):
    """round-to-nearest-even for non-negative array x."""
    fl = np.floor(x)
    fr = x - fl
    even = (np.mod(fl, 2.0) == 0.0)
    rup = np.where(fr < 0.5, 0.0, np.where(fr > 0.5, 1.0, np.where(even, 0.0, 1.0)))
    return fl + rup

def q_e4m3_vec(v):
    """vectorised E4M3 activation quant (real->real), RNE + saturate 448."""
    v = np.asarray(v, dtype=np.float64)
    nz = v != 0.0
    s = v < 0.0
    av = np.abs(np.where(nz, v, 1.0))
    _, exp_i = np.frexp(av)
    E = exp_i - 1                              # floor(log2(av))
    sub = nz & (E < -6)
    ovf = nz & (E > 8)
    nrm = nz & ~sub & ~ovf
    q = np.zeros_like(v)
    # subnormal region
    quantum_sub = 2.0 ** -9
    q = np.where(sub, _rne_vec(np.where(sub, av / quantum_sub, 0.0)) * quantum_sub, q)
    # normal region
    Ec = np.where(nrm, E, 0)
    quantum = np.exp2((Ec - 3).astype(np.float64))
    mant = _rne_vec(np.where(nrm, av / quantum, 0.0))
    adj = nrm & (mant >= 16)
    Ec2 = np.where(adj, Ec + 1, Ec)
    mant2 = np.where(adj, 8.0, mant)
    qn = mant2 * np.exp2((Ec2 - 3).astype(np.float64))
    sat = nrm & ((Ec2 > 8) | ((Ec2 == 8) & (mant2 >= 15)))
    qn = np.where(sat, 448.0, qn)
    q = np.where(nrm, qn, q)
    # overflow region
    q = np.where(ovf, 448.0, q)
    q = np.where(s, -q, q)
    return np.where(nz, q, 0.0)

# ============================================================================
# (B) E4M3 decode (weight code -> real).  OCP E4M3 1s.4e(bias7).3m; NaN,zero->0.
# ============================================================================
def _e4m3_dec_scalar(c):
    c &= 0xFF
    s = (c >> 7) & 1; e = (c >> 3) & 0xF; m = c & 0x7
    if e == 0xF and m == 0x7:
        val = 0.0
    elif e == 0 and m == 0:
        val = 0.0
    elif e == 0:
        val = m * (2.0 ** -9)
    else:
        val = (1.0 + m / 8.0) * (2.0 ** (e - 7))
    return -val if s else val

# 256-entry decode LUT (float64)
E4M3_LUT = np.array([_e4m3_dec_scalar(c) for c in range(256)], dtype=np.float64)

# ============================================================================
# (C) E4M3 quantiser for activations (real -> real), RNE + saturate to 448.
# ============================================================================
def _rne_nonneg(x):
    fl = int(x)                 # trunc toward zero; x>=0 -> floor
    fr = x - fl
    if fr < 0.5:
        return fl
    if fr > 0.5:
        return fl + 1
    return fl if (fl % 2 == 0) else fl + 1

def q_e4m3(v):
    if v == 0.0:
        return 0.0
    s = v < 0.0
    av = abs(v)
    E = 0
    if av >= 1.0:
        while av >= 2.0 ** (E + 1):
            E += 1
    else:
        while av < 2.0 ** E:
            E -= 1
    if E < -6:
        quantum = 2.0 ** -9
        q = _rne_nonneg(av / quantum) * quantum
    elif E > 8:
        q = 448.0
    else:
        quantum = 2.0 ** (E - 3)
        mant = _rne_nonneg(av / quantum)
        if mant >= 16:
            E += 1; mant = 8
        if E > 8:
            q = 448.0
        elif E == 8 and mant >= 15:
            q = 448.0
        else:
            q = mant * (2.0 ** (E - 3))
    return -q if s else q

def dshift(emx):
    """per-token pow2 activation scale exponent from the max bf16 exp field."""
    if emx == 0:
        return 0
    sh = 134 - emx
    if sh > 127:
        sh = 127
    if sh < -128:
        sh = -128
    return sh

# ============================================================================
# (D) [128,128] block-scaled dynamic-activation FP8 GEMM (float64 accumulate)
#     y[o] = ( SUM_kb  w_scale[o//BLK][kb] *
#                SUM_{k in block kb} e4m3_dec(W[o][k]) * q_e4m3(a[k]*2^ash) )
#            * 2^-ash        ->  bf16
#     W_ok : float64 [OUT][K] already E4M3-decoded weights.
#     asrc : uint16 [K] bf16 activation codes.
#     scale: float64 [n_out_blk][n_k_blk] dequant scales (already b2real'd).
# ============================================================================
def fp8_gemm(W_ok, asrc_codes, scale):
    OUT, K = W_ok.shape
    nkb = (K + BLK - 1) // BLK
    codes32 = np.asarray(asrc_codes, dtype=np.uint32)
    # per-token pow2 activation scale from max bf16 exp field
    emx = int(((codes32 >> 7) & 0xFF).max()) if K else 0
    ash = dshift(emx)
    pow_up = 2.0 ** ash
    pow_dn = 2.0 ** (-ash)
    # dynamic per-token E4M3 quant of activations
    aq = q_e4m3_vec(b2real_vec(asrc_codes) * pow_up)
    # block accumulation.  scale is [n_out_blk][n_k_blk]; uniform families pass
    # [1][1] (broadcast over all blocks), dense gate/up pass [n_out_blk][1],
    # dense down passes [1][n_k_blk].  Clamp indices so a uniform scale rides
    # every K-block even when K spans >1 block (matches the RTL contract).
    R, C = scale.shape
    deq = np.zeros(OUT, dtype=np.float64)
    out_blk = np.minimum(np.arange(OUT) // BLK, R - 1)
    for kb in range(nkb):
        lo = kb * BLK
        hi = min((kb + 1) * BLK, K)
        part = W_ok[:, lo:hi] @ aq[lo:hi]              # [OUT]
        sc = scale[out_blk, min(kb, C - 1)]             # [OUT]
        deq += part * sc
    deq *= pow_dn
    codes = real2b_vec(deq)
    return codes, b2real_vec(codes)

# ============================================================================
# (E) deterministic stimulus generators (mirror the TB hash generators)
# ============================================================================
def _hash(seed, mult):
    a = (seed * 2654435761) & MASK32
    b = (seed << 13) & MASK32
    c = (seed * mult) & MASK32
    return (a ^ b ^ c) & MASK32

def gen_bf16(seed, band):
    h = _hash(seed, 40503)
    s = (h >> 3) & 1
    if band == 1:
        e = 125 + ((h >> 4) & 7)
    else:
        e = 124 + ((h >> 4) & 3)
    m = (h >> 6) & 0x7F
    return ((s << 15) | ((e & 0xFF) << 7) | m) & 0xFFFF

def gen_e4m3(seed, band):
    h = _hash(seed, 40503)
    s = (h >> 3) & 1
    if band == 1:
        e = 7 + ((h >> 4) & 1)
    else:
        e = 6 + ((h >> 4) & 1)
    m = (h >> 10) & 0x7
    return ((s << 7) | ((e & 0xF) << 3) | m) & 0xFF

def gen_scale(seed):
    h = _hash(seed, 22229)
    e = 122 + ((h >> 2) & 1)
    m = (h >> 4) & 0x7F
    return ((e & 0xFF) << 7) | m           # bf16 code, sign 0

# ---- vectorised generators (numpy int64 seeds -> code arrays) ----
def _hash_vec(seed, mult):
    seed = np.asarray(seed, dtype=np.int64)
    a = (seed * 2654435761) & MASK32
    b = (seed << 13) & MASK32
    c = (seed * mult) & MASK32
    return (a ^ b ^ c) & MASK32

def gen_bf16_vec(seed, band):
    h = _hash_vec(seed, 40503)
    s = (h >> 3) & 1
    e = (125 + ((h >> 4) & 7)) if band == 1 else (124 + ((h >> 4) & 3))
    m = (h >> 6) & 0x7F
    return (((s << 15) | ((e & 0xFF) << 7) | m) & 0xFFFF).astype(np.uint16)

def gen_e4m3_vec(seed, band):
    h = _hash_vec(seed, 40503)
    s = (h >> 3) & 1
    e = (7 + ((h >> 4) & 1)) if band == 1 else (6 + ((h >> 4) & 1))
    m = (h >> 10) & 0x7
    return (((s << 7) | ((e & 0xF) << 3) | m) & 0xFF).astype(np.uint8)

def gen_scale_vec(seed):
    h = _hash_vec(seed, 22229)
    e = 122 + ((h >> 2) & 1)
    m = (h >> 4) & 0x7F
    return (((e & 0xFF) << 7) | m).astype(np.uint16)


class Weights:
    pass


def build_stimulus(seed0, band):
    """Replicate test/glm_model_fp8_tb.v build_stimulus sc-counter order EXACTLY,
       generating each contiguous run of seeds in bulk (numpy).  Row-major
       (C-order) reshape matches the TB's (i outer, j inner) fill order."""
    W = Weights()
    sc = [seed0]                                # boxed running counter

    def _seeds(n):
        s = np.arange(sc[0], sc[0] + n, dtype=np.int64)
        sc[0] += n
        return s

    def bf(shape):                               # bulk bf16 codes
        n = int(np.prod(shape))
        return gen_bf16_vec(_seeds(n), band).reshape(shape)

    def ee(shape):                               # bulk e4m3 codes
        n = int(np.prod(shape))
        return gen_e4m3_vec(_seeds(n), band).reshape(shape)

    def ss(shape):                               # bulk scale codes
        n = int(np.prod(shape))
        return gen_scale_vec(_seeds(n)).reshape(shape)

    def skip(n):                                 # advance counter (dead weights)
        sc[0] += n

    # embedding [VOCAB][MODEL_DIM]
    W.EMB = bf((VOCAB, MODEL_DIM))

    W.G1 = np.empty((L, MODEL_DIM), dtype=np.uint16)
    W.G2 = np.empty((L, MODEL_DIM), dtype=np.uint16)
    W.W_dq = np.empty((L, Q_LORA, MODEL_DIM), dtype=np.uint8)
    W.W_uq = np.empty((L, HQK, Q_LORA), dtype=np.uint8)
    W.W_uk = np.empty((L, HNOPE, KV_LORA), dtype=np.uint8)
    W.W_uv = np.empty((L, HV, KV_LORA), dtype=np.uint8)
    W.W_o = np.empty((L, MODEL_DIM, HV), dtype=np.uint8)
    W.ScW_dq = np.empty(L, dtype=np.uint16); W.ScW_uq = np.empty(L, dtype=np.uint16)
    W.ScW_uk = np.empty(L, dtype=np.uint16); W.ScW_uv = np.empty(L, dtype=np.uint16)
    W.ScW_o = np.empty(L, dtype=np.uint16)
    W.CKV = np.empty((L, S_MAX, KV_LORA), dtype=np.uint16)
    W.KRP = np.empty((L, S_MAX, ROPE), dtype=np.uint16)
    W.Wg = np.empty((L, N_EXPERT, MODEL_DIM), dtype=np.uint8)   # router, [expert][k]
    W.ScWg = np.empty(L, dtype=np.uint16)
    W.Dg = np.empty((L, INTER_DENSE, MODEL_DIM), dtype=np.uint8)
    W.Du = np.empty((L, INTER_DENSE, MODEL_DIM), dtype=np.uint8)
    W.Dd = np.empty((L, MODEL_DIM, INTER_DENSE), dtype=np.uint8)
    W.ScDg = np.empty((L, FF_NB_D), dtype=np.uint16)
    W.ScDu = np.empty((L, FF_NB_D), dtype=np.uint16)
    W.ScDd = np.empty((L, FF_NB_D), dtype=np.uint16)
    W.Mg = np.empty((L, N_EXPERT, INTER_MOE, MODEL_DIM), dtype=np.uint8)
    W.Mu = np.empty((L, N_EXPERT, INTER_MOE, MODEL_DIM), dtype=np.uint8)
    W.Md = np.empty((L, N_EXPERT, MODEL_DIM, INTER_MOE), dtype=np.uint8)
    W.ScMg = np.empty((L, N_EXPERT), dtype=np.uint16)
    W.ScMu = np.empty((L, N_EXPERT), dtype=np.uint16)
    W.ScMd = np.empty((L, N_EXPERT), dtype=np.uint16)
    W.SHg = np.empty((L, INTER_MOE, MODEL_DIM), dtype=np.uint8)
    W.SHu = np.empty((L, INTER_MOE, MODEL_DIM), dtype=np.uint8)
    W.SHd = np.empty((L, MODEL_DIM, INTER_MOE), dtype=np.uint8)
    W.ScSHg = np.empty(L, dtype=np.uint16); W.ScSHu = np.empty(L, dtype=np.uint16)
    W.ScSHd = np.empty(L, dtype=np.uint16)

    for ly in range(L):
        W.G1[ly] = bf(MODEL_DIM)
        W.G2[ly] = bf(MODEL_DIM)
        W.W_dq[ly] = ee((Q_LORA, MODEL_DIM))
        W.W_uq[ly] = ee((HQK, Q_LORA))
        skip(KV_LORA * MODEL_DIM)                # W_dkv (dead)
        skip(ROPE * MODEL_DIM)                   # W_kr  (dead)
        W.W_uk[ly] = ee((HNOPE, KV_LORA))
        W.W_uv[ly] = ee((HV, KV_LORA))
        W.W_o[ly] = ee((MODEL_DIM, HV))
        W.ScW_dq[ly] = ss(1)[0]; W.ScW_uq[ly] = ss(1)[0]
        skip(2)                                  # ScW_dkv, ScW_kr (dead)
        W.ScW_uk[ly] = ss(1)[0]; W.ScW_uv[ly] = ss(1)[0]; W.ScW_o[ly] = ss(1)[0]
        W.CKV[ly] = bf((S_MAX, KV_LORA))
        W.KRP[ly] = bf((S_MAX, ROPE))
        # router filled [MODEL_DIM][N_EXPERT] (i=k outer, j=expert inner) -> transpose
        W.Wg[ly] = ee((MODEL_DIM, N_EXPERT)).T
        W.ScWg[ly] = ss(1)[0]
        W.Dg[ly] = ee((INTER_DENSE, MODEL_DIM))
        W.Du[ly] = ee((INTER_DENSE, MODEL_DIM))
        W.Dd[ly] = ee((MODEL_DIM, INTER_DENSE))
        W.ScDg[ly] = ss(FF_NB_D)
        W.ScDu[ly] = ss(FF_NB_D)
        W.ScDd[ly] = ss(FF_NB_D)
        for e in range(N_EXPERT):
            W.Mg[ly, e] = ee((INTER_MOE, MODEL_DIM))
            W.Mu[ly, e] = ee((INTER_MOE, MODEL_DIM))
            W.Md[ly, e] = ee((MODEL_DIM, INTER_MOE))
            W.ScMg[ly, e] = ss(1)[0]; W.ScMu[ly, e] = ss(1)[0]; W.ScMd[ly, e] = ss(1)[0]
        W.SHg[ly] = ee((INTER_MOE, MODEL_DIM))
        W.SHu[ly] = ee((INTER_MOE, MODEL_DIM))
        W.SHd[ly] = ee((MODEL_DIM, INTER_MOE))
        W.ScSHg[ly] = ss(1)[0]; W.ScSHu[ly] = ss(1)[0]; W.ScSHd[ly] = ss(1)[0]

    W.GF = bf(MODEL_DIM)
    W.Wlm = bf((VOCAB, MODEL_DIM))

    W.total_sc = sc[0] - seed0
    return W

# ============================================================================
# (F) the assembled forward pass (independent transformer structuring)
# ============================================================================
def _dec(codes8):
    """E4M3 code array -> decoded float64 (via LUT), same shape."""
    return E4M3_LUT[np.asarray(codes8, dtype=np.uint8)]

def rmsnorm(x_codes, gamma_codes):
    """x,gamma bf16 codes -> bf16 codes.  y=x/rms * gamma ; rms over fp64."""
    xr = b2real_vec(x_codes)
    ss = float(np.dot(xr, xr))
    inv = 1.0 / math.sqrt(ss / len(x_codes) + EPS)
    gr = b2real_vec(gamma_codes)
    return real2b_vec(xr * inv * gr)

def rmsnorm_nog(x_codes):
    """RMSNorm WITHOUT gamma (q-lora / ckv latent norm) -> bf16 codes."""
    xr = b2real_vec(x_codes)
    ss = float(np.dot(xr, xr))
    inv = 1.0 / math.sqrt(ss / len(x_codes) + EPS)
    return real2b_vec(xr * inv)

def silu(x):
    return x / (1.0 + math.exp(-x))

def sigmoid(x):
    return 1.0 / (1.0 + math.exp(-x))


def attention(W, ly, nrm1_codes, tpos, Sg):
    """MLA attention over the (already RMSNorm'd) hidden -> real MODEL_DIM vec."""
    Wdq = _dec(W.W_dq[ly]);  Wuq = _dec(W.W_uq[ly])
    Wuk = _dec(W.W_uk[ly]);  Wuv = _dec(W.W_uv[ly]);  Wo = _dec(W.W_o[ly])
    s_dq = np.full((1, 1), b2real(W.ScW_dq[ly]))
    s_uq = np.full((1, 1), b2real(W.ScW_uq[ly]))
    s_uk = np.full((1, 1), b2real(W.ScW_uk[ly]))
    s_uv = np.full((1, 1), b2real(W.ScW_uv[ly]))
    s_o = np.full((1, 1), b2real(W.ScW_o[ly]))

    # q down-projection -> latent RMSNorm -> up-projection
    q_lora, _ = fp8_gemm(Wdq, nrm1_codes, s_dq)          # [Q_LORA]
    q_ln = rmsnorm_nog(q_lora)                            # [Q_LORA]
    q_full, _ = fp8_gemm(Wuq, q_ln, s_uq)                # [HQK]

    # per-head q: [NOPE | RoPE(rotated at query position tpos)]
    qfr = b2real_vec(q_full)
    gq = np.zeros(HQK, dtype=np.float64)
    for hd in range(H_HEADS):
        base = hd * QK_DIM
        for d in range(NOPE):
            gq[base + d] = qfr[base + d]
        for pr in range(ROPE // 2):
            invf = 1.0 / (float(THETA) ** ((2.0 * pr) / ROPE))
            ang = tpos * invf
            c = math.cos(ang); sn = math.sin(ang)
            x0 = qfr[base + NOPE + 2 * pr]
            x1 = qfr[base + NOPE + 2 * pr + 1]
            gq[base + NOPE + 2 * pr]     = bf16(x0 * c - x1 * sn)
            gq[base + NOPE + 2 * pr + 1] = bf16(x0 * sn + x1 * c)

    # keys / values from the KV latent cache (Sg valid slots)
    gK = np.zeros((H_HEADS, Sg, QK_DIM), dtype=np.float64)
    gV = np.zeros((H_HEADS, Sg, V_DIM), dtype=np.float64)
    for sd in range(Sg):
        ckvn = rmsnorm_nog(W.CKV[ly, sd])                # [KV_LORA]
        knope, _ = fp8_gemm(Wuk, ckvn, s_uk)             # [HNOPE]
        v, _ = fp8_gemm(Wuv, ckvn, s_uv)                 # [HV]
        knr = b2real_vec(knope); vr = b2real_vec(v)
        krp = b2real_vec(W.KRP[ly, sd])                  # cached (pre-rotated) k_rope
        for hd in range(H_HEADS):
            for d in range(NOPE):
                gK[hd, sd, d] = knr[hd * NOPE + d]
            for d in range(ROPE):
                gK[hd, sd, NOPE + d] = krp[d]
            for d in range(V_DIM):
                gV[hd, sd, d] = vr[hd * V_DIM + d]

    # scores (no 1/sqrt(d) scale in this slice's contract) -> bf16
    gctx = np.zeros(HV, dtype=np.float64)
    for hd in range(H_HEADS):
        sc = np.zeros(Sg, dtype=np.float64)
        for sd in range(Sg):
            acc = float(np.dot(gq[hd * QK_DIM:(hd + 1) * QK_DIM], gK[hd, sd]))
            sc[sd] = bf16(acc)
        mx = sc.max()
        ex = np.array([math.exp(sc[sd] - mx) for sd in range(Sg)])
        ssum = float(ex.sum())
        p = np.array([bf16(ex[sd] / ssum) for sd in range(Sg)])
        for d in range(V_DIM):
            acc = float(np.dot(p, gV[hd, :, d]))
            gctx[hd * V_DIM + d] = bf16(acc)

    ctx_codes = real2b_vec(gctx)
    _, attn_real = fp8_gemm(Wo, ctx_codes, s_o)          # [MODEL_DIM] real
    return attn_real


def swiglu(nrm2_codes, Wg_dec, Wu_dec, Wd_dec, sg, su, sd_):
    """one SwiGLU expert: down( silu(gate)*up ) with the contract's bf16 points."""
    gate, _ = fp8_gemm(Wg_dec, nrm2_codes, sg)
    up, _ = fp8_gemm(Wu_dec, nrm2_codes, su)
    gr = b2real_vec(gate); ur = b2real_vec(up)
    sil = gr / (1.0 + np.exp(-gr))                 # SiLU
    hh = b2real_vec(real2b_vec(sil))               # bf16-round SiLU (contract point)
    h = real2b_vec(hh * ur)                         # bf16-round (silu*up)
    _, y_real = fp8_gemm(Wd_dec, h, sd_)
    return y_real


def dense_ffn(W, ly, nrm2_codes):
    Dg = _dec(W.Dg[ly]); Du = _dec(W.Du[ly]); Dd = _dec(W.Dd[ly])
    # gate/up scale: per OUTPUT block (INTER_DENSE=256 -> 2 out-blocks), single K-blk
    sg = np.array([[b2real(W.ScDg[ly, ob])] for ob in range(FF_NB_D)])   # [2][1]
    su = np.array([[b2real(W.ScDu[ly, ob])] for ob in range(FF_NB_D)])
    # down scale: single out-block (MODEL_DIM=128), per K-block (INTER_DENSE=256 ->2)
    sd_ = np.array([[b2real(W.ScDd[ly, kb]) for kb in range(FF_NB_D)]])  # [1][2]
    return swiglu(nrm2_codes, Dg, Du, Dd, sg, su, sd_)


def moe_ffn(W, ly, nrm2_codes):
    # router: sigmoid gate over N_EXPERT
    Wg = _dec(W.Wg[ly])
    s_g = np.full((1, 1), b2real(W.ScWg[ly]))
    rlog, _ = fp8_gemm(Wg, nrm2_codes, s_g)              # [N_EXPERT]
    rlr = b2real_vec(rlog)
    gate = b2real_vec(real2b_vec(1.0 / (1.0 + np.exp(-rlr))))   # bf16(sigmoid)
    # top-k (K=2), strict-greater compare -> lower index on tie
    used = [False] * N_EXPERT
    idx = []; gtop = []
    for _ in range(TOPK):
        bestj = -1; bestv = -1e30
        for j in range(N_EXPERT):
            if not used[j] and gate[j] > bestv:
                bestv = gate[j]; bestj = j
        idx.append(bestj); gtop.append(gate[bestj]); used[bestj] = True
    ssum = sum(gtop)
    tw = [bf16((gtop[i] / ssum) * RSCALE) for i in range(TOPK)]
    facc = np.zeros(MODEL_DIM, dtype=np.float64)
    for i in range(TOPK):
        e = idx[i]
        Mg = _dec(W.Mg[ly, e]); Mu = _dec(W.Mu[ly, e]); Md = _dec(W.Md[ly, e])
        sg = np.full((1, 1), b2real(W.ScMg[ly, e]))
        su = np.full((1, 1), b2real(W.ScMu[ly, e]))
        sd_ = np.full((1, 1), b2real(W.ScMd[ly, e]))
        y = swiglu(nrm2_codes, Mg, Mu, Md, sg, su, sd_)
        facc += tw[i] * y
    # shared expert (weight 1)
    SHg = _dec(W.SHg[ly]); SHu = _dec(W.SHu[ly]); SHd = _dec(W.SHd[ly])
    sg = np.full((1, 1), b2real(W.ScSHg[ly]))
    su = np.full((1, 1), b2real(W.ScSHu[ly]))
    sd_ = np.full((1, 1), b2real(W.ScSHd[ly]))
    facc += swiglu(nrm2_codes, SHg, SHu, SHd, sg, su, sd_)
    return real2b_vec(facc)


def forward(W, tok, tpos, Sg, stages=None):
    """full GLM-5.2-FP8 forward for one token -> (logit_codes[VOCAB], argmax)."""
    x = W.EMB[tok].copy()                                # bf16 codes [MODEL_DIM]
    for ly in range(L):
        is_moe = (ly >= N_DENSE)
        nrm1 = rmsnorm(x, W.G1[ly])
        attn_real = attention(W, ly, nrm1, tpos, Sg)
        h = real2b_vec(b2real_vec(x) + attn_real)        # bf16 residual after attn
        nrm2 = rmsnorm(h, W.G2[ly])
        if not is_moe:
            ffn_real = dense_ffn(W, ly, nrm2)            # real
            x = real2b_vec(b2real_vec(h) + ffn_real)
        else:
            ffn_codes = moe_ffn(W, ly, nrm2)             # bf16 codes
            ffn_real = b2real_vec(ffn_codes)
            x = real2b_vec(b2real_vec(h) + ffn_real)
        if stages is not None:
            stages.append(dict(layer=ly,
                               nrm1=nrm1.copy(), attn=real2b_vec(attn_real),
                               h=h.copy(), nrm2=nrm2.copy(),
                               ffn=real2b_vec(ffn_real), x=x.copy()))
    # final RMSNorm + LM head
    xn = rmsnorm(x, W.GF)
    xnr = b2real_vec(xn)
    Wlm_real = b2real_vec(W.Wlm)                          # [VOCAB, MODEL_DIM]
    logits = real2b_vec(Wlm_real @ xnr)                  # bf16 per logit
    logit_real = b2real_vec(logits)
    # argmax: first strict maximum (lowest index on tie)
    am = 0; best = logit_real[0]
    for v in range(1, VOCAB):
        if logit_real[v] > best:
            best = logit_real[v]; am = v
    return logits, am, logit_real


# committed test vectors (mirror the TB initial block)
TESTS = [
    dict(seed0=500,   band=0, tok=7,   tpos=0,  Sg=1,     label="tok7 pos0 S1"),
    dict(seed0=7000,  band=0, tok=100, tpos=37, Sg=3,     label="tok100 pos37 S3"),
    dict(seed0=90000, band=1, tok=255, tpos=42, Sg=S_MAX, label="tok255 pos42 Smax b1"),
]


def run_all(verbose=True):
    results = []
    for t in TESTS:
        W = build_stimulus(t["seed0"], t["band"])
        logits, am, lr = forward(W, t["tok"], t["tpos"], t["Sg"])
        results.append(dict(label=t["label"], tok=t["tok"], tpos=t["tpos"],
                            Sg=t["Sg"], band=t["band"], sc=W.total_sc,
                            logit_codes=logits, argmax=am, logit_real=lr))
        if verbose:
            print(f"[np] {t['label']:24s}  argmax={am:3d}  "
                  f"best={lr[am]:.4f}  sc_consumed={W.total_sc}")
    return results


if __name__ == "__main__":
    run_all()
